name: ci

on:
  push:
    branches:
      - main
jobs:
  TestAndBuild:
      env:
        DOCKER_IMAGE_NAME: acll19/quarkus-gcp-cloud-run-demo
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up gradle
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

        - name: Run tests
          run: ./gradlew test

        - name: Build
          run: | 
            cp src/main/docker/Dockerfile.native Dockerfile
            ./gradlew -x test build -Dquarkus.package.type=native

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: us-east4-docker.pkg.dev
            username: _json_key
            password: ${{ secrets.GAR_JSON_KEY }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ env.DOCKER_IMAGE_NAME }}:latest

        - name: Deploy to Cloud Run
            id: deploy
            uses: google-github-actions/deploy-cloudrun@main
            with:
              service: quarkus-gcp-cloud-run-demo 
              image: gcr.io/my-images/quarkus-gcp-cloud-run-demo
              credentials: ${{ secrets.GCP_SA_KEY }}

        - name: Use Output
            run: curl "${{ steps.deploy.outputs.url }}"