name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Run tests
          run: echo 'Running tests'
  