name: ci

on:
  push:
    branches:
      - main
jobs:
  Test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Set up gradle
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Run tests
          run: ./gradlew test
  Build:
      runs-on: ubuntu-latest
      steps:
        - name: Build
          run: | 
            cp src/main/docker/Dockerfile.native Dockerfile
            ./gradlew -x test build -Dquarkus.package.type=native
        - name: Set docker image name env
          run: | 
            echo ::set-env name=DOCKER_IMAGE_NAME::acll19/quarkus-gcp-cloud-run-demo
            echo ::set-env name=DOCKER_TAG_VERSION::$(echo $GITHUB_RUN_NUMBER)
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_API_KEY }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}
              ${{ env.DOCKER_IMAGE_NAME }}:latest